discordToken: "token"
embed:
  cancelIcon: "https://maxouxax.me/favicon.ico"
  footerText: "Raymond"
  footerIconUrl: "https://maxouxax.me/favicon.ico"
gameName: "Raymond"
websiteUrl: "https://maxouxax.me"
univConfig:
  authUrl: ""
  dataUrl: ""
  username: ""
  password: ""
  clockEmoji: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Icons8_flat_clock.svg/1200px-Icons8_flat_clock.svg.png"